spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test2?serverTimezone=GMT%2B8
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8
    basename: message_zh_CN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
